### ISSUE TITLE
Can not open the GUI wallet in Mac

### ISSUE THREAD

**Issue by GranitNiti** [iron-fish/node-app#265]
Version: Iron.Fish.Node.App-darwin-x64-1.0.2

After installing and opening I get the following message:

Uncaught Exception:
Error: Could not get code signature for running application
at Object.initialize (/Applications/Iron Fish Node App.app/Contents/Resources/app/.webpack/main/index.js:2:1015667)
at 20665 (/Applications/Iron Fish Node App.app/Contents/Resources/app/.webpack/main/index.js:2:1017751)
at __webpack_require__ (/Applications/Iron Fish Node App.app/Contents/Resources/app/.webpack/main/index.js:2:1284072)
at 20646 (/Applications/Iron Fish Node App.app/Contents/Resources/app/.webpack/main/index.js:2:1020553)
at __webpack_require__ (/Applications/Iron Fish Node App.app/Contents/Resources/app/.webpack/main/index.js:2:1284072)
at /Applications/Iron Fish Node App.app/Contents/Resources/app/.webpack/main/index.js:2:1285013
at /Applications/Iron Fish Node App.app/Contents/Resources/app/.webpack/main/index.js:2:1285081
at Object.<anonymous> (/Applications/Iron Fish Node App.app/Contents/Resources/app/.webpack/main/index.js:2:1285120)
at Module._compile (node:internal/modules/cjs/loader:1118:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)

**Comment by azhurauski-sc** [comment]
That is know issue and we working to fix it. Please do not submit issues while app is no officially released.
